
name: CI
on: [ push ]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install references
        run: sudo apt-get install libgtest-dev -y && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && cd lib && sudo cp *.a /usr/lib && sudo apt-get install -y cppcheck && sudo apt-get install valgrind && sudo apt-get install -y lcov && sudo apt-get install -y gcovr

        
      - name: build
        run: cmake . && make 

      - name: valgrind
        run:  valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all -s -q ./main ./tests_forked

      - name: static analys
        run: cppcheck -q --enable=all --platform=unix64 --check-config --suppress=missingIncludeSystem libs/array_search/include/* libs/array_search/src/* libs/array_search_forked/include/* libs/array_search_forked/src/* 

      - name: tests
        run:  ./main && ./tests_forked && lcov -t "IW_2" -o coverage.txt -c -d . && cp coverage.txt ../

      
